--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/SpawnerShopUI
build-by-default: true
branches:
- master
projects:
  SpawnerShopUI:
    path: ""
    icon: "SSUI_Icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
